version: "3.8"

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./:/opt/app
      - /opt/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "develop"]
